<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCulw3fh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCulw3fh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCulw3fh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCulw3fh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCulw3fh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Culw3fh',
    'container.build_id' => 'b26b02f6',
    'container.build_time' => 1582817392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCulw3fh');
